### ISSUE TITLE
ValueError: word_ids() is not available when using Python-based tokenizers

### ISSUE THREAD

**Issue by quangdaist01** [VinAIResearch/PhoNER_COVID19#2]
Hello!,
Thanks for publishing the dataset.

I'm trying to replicate the results reported in the paper. 
I had some trouble when encoding labels from original tokens to tokenized tokens. The tokens ids length are usually longer than the word tokens since they can be split into multiple sub-word tokens. For example, the word "Bệnh" is splitted into 'Be@@', '̣@@', '<unk>', 'nh', which also causes the corresponding label to be longer.

The problem can be easily solved if the tokenizer output contains 'word_ids' attribute which indicates which token the each input_id comes from. This is what most tokenizers in huggingface supports.

This function is taken from run_ner.py in example code of huggingface repo:
```
    def tokenize_and_align_labels(examples):
        tokenized_inputs = tokenizer(
            examples[text_column_name],
            padding=padding,
            truncation=True,
            max_length=data_args.max_seq_length,
            # We use this argument because the texts in our dataset are lists of words (with a label for each word).
            is_split_into_words=True,
        )
        labels = []
        for i, label in enumerate(examples[label_column_name]):
            word_ids = tokenized_inputs.word_ids(batch_index=i)
            previous_word_idx = None
            label_ids = []
            for word_idx in word_ids:
                # Special tokens have a word id that is None. We set the label to -100 so they are automatically
                # ignored in the loss function.
                if word_idx is None:
                    label_ids.append(-100)
                # We set the label for the first token of each word.
                elif word_idx != previous_word_idx:
                    label_ids.append(label_to_id[label[word_idx]])
                # For the other tokens in a word, we set the label to either the current label or -100, depending on
                # the label_all_tokens flag.
                else:
                    if data_args.label_all_tokens:
                        label_ids.append(b_to_i_label[label_to_id[label[word_idx]]])
                    else:
                        label_ids.append(-100)
                previous_word_idx = word_idx

            labels.append(label_ids)
        tokenized_inputs["labels"] = labels
        return tokenized_inputs
```

When I use PhoBERT tokenizer, I get the error like this:
```
 0%|          | 0/6 [00:00<?, ?ba/s]
Traceback (most recent call last):
  File "C:\Users\quang\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-66d85e73c564>", line 101, in <module>
    train_tokenized_datasets = train_dataset.map(tokenize_and_align_labels, batched=True)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 2035, in map
    return self._map_single(
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 521, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 488, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\fingerprint.py", line 406, in wrapper
    out = func(self, *args, **kwargs)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 2403, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 2290, in apply_function_on_filtered_inputs
    function(*fn_args, effective_indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\datasets\arrow_dataset.py", line 1990, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "<ipython-input-7-66d85e73c564>", line 75, in tokenize_and_align_labels
    word_ids = tokenized_inputs.word_ids(batch_index=i)
  File "C:\Users\quang\PycharmProjects\DeepGamingAI_FPS\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 353, in word_ids
    raise ValueError("word_ids() is not available when using Python-based tokenizers")
ValueError: word_ids() is not available when using Python-based tokenizers
```

Can you suggest a solution to this problem? 
Thanks for reading!

**Comment by joey234** [comment]
Hi there, thank you for your interest.
As PhoBERT does not support fast tokenizer, please use the old version of the `run_ner.py` script. You can follow the instruction here: https://github.com/huggingface/transformers/tree/master/examples/legacy/token-classification

Otherwise, here is an example of the running script for reference
```
#Preprocessing
export MAX_LENGTH=128
export BERT_MODEL=vinai/phobert-base
python preprocess.py data/train_word.txt $BERT_MODEL $MAX_LENGTH > train.txt
python preprocess.py data/dev_word.txt $BERT_MODEL $MAX_LENGTH > dev.txt
python preprocess.py data/test_word.txt $BERT_MODEL $MAX_LENGTH > test.txt
cat train.txt dev.txt test.txt | cut -d " " -f 2 | grep -v "^$"| sort | uniq > labels.txt

export BATCH_SIZE=64
export NUM_EPOCHS=30

for SEED in 1
do
    export OUTPUT_DIR=nercovid-phobert-base-ep
    export OUTPUT_DIR=$OUTPUT_DIR$NUM_EPOCHS"_"$SEED
    python run_ner.py \
    --task_type NER \
    --data_dir . \
    --labels ./labels.txt \
    --model_name_or_path $BERT_MODEL \
    --output_dir $OUTPUT_DIR \
    --max_seq_length  $MAX_LENGTH \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $BATCH_SIZE \
    --seed $SEED \
    --do_train \
    --do_eval \
    --do_predict \
    --evaluation_strategy epoch \
    --logging_dir $OUTPUT_DIR  \
    --load_best_model_at_end
done
```
Hope it helps!

**Comment by quangdaist01** [comment]
Thank you for your quick support. I just tried and it worked like a charm!.
Have a nice day!!
